

FROM node:20-slim

WORKDIR /app

# Dependências nativas para build e runtime
RUN apt-get update && apt-get install -y python3 make g++ gcc build-essential libsqlite3-dev

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN npm run build

ENV NODE_ENV=production
ENV NUXT_PORT=3000
EXPOSE 3000

CMD ["npm", "start"]
